[package]
name = "discord_ts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.2.20", features = ["derive"]}
chrono = "0.4.22"
copypasta = "0.8.1"
copypasta-ext = "0.3.9"